spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minicampus?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: thehd123
  
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
            
logging:
  level:
    root: info
    
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

